name: ExamFile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  firebase_core: ^3.3.0
  lottie: ^3.1.2
  dio: ^5.6.0
  smooth_page_indicator: ^1.2.0+3
  firebase_auth: ^5.1.4
  zoom_tap_animation: ^1.1.0
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.5
  easy_stepper: ^0.8.5+1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  video_player: ^2.9.1
  intl: ^0.19.0
  provider: ^6.1.2
  file_picker: ^8.0.7
  image_picker: ^1.1.2
  equatable: ^2.0.5
  firebase_storage: ^12.1.3
  refresh: ^1.0.1
  hive: ^2.2.3
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
#  file: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/images/splash/
